// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using carPool.Context;

namespace carPool.Migrations
{
    [DbContext(typeof(CarPoolContext))]
    partial class CarPoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("carPool.Context.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Score");

                    b.Property<string>("SessionId");

                    b.HasKey("Id");

                    b.ToTable("Ride");
                });

            modelBuilder.Entity("carPool.Context.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("carPool.Context.Answer", b =>
                {
                    b.HasOne("carPool.Context.Ride")
                        .WithMany("Answer")
                        .HasForeignKey("RideId");
                });
#pragma warning restore 612, 618
        }
    }
}
