// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using carPool.Context;

namespace carPool.Migrations
{
    [DbContext(typeof(CarPoolContext))]
    [Migration("20190717221502_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("carPool.Context", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

   
                    b.Property<int?>("RideId");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                });

            modelBuilder.Entity("carPool.Context.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

    

                    b.ToTable("Ride");
                });

            modelBuilder.Entity("carPool.Context.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("carPool.Context.Answer", b =>
                {
                    b.HasOne("carPool.Context.Ride")
                        .HasForeignKey("RideId");
                });
#pragma warning restore 612, 618
        }
    }
}
